version: 1
formatters:
    rootFormatter:
        format:      "%(asctime)s.%(msecs)03d  %(name)-15s  %(levelname)-10s  %(message)s"
        datefmt:     '%Y-%m-%d %H:%M:%S'
handlers:
    consoleHandler:
        class:       logging.StreamHandler
        formatter:   rootFormatter
        stream:      ext://sys.stdout
    fileHandler:
        class:       logging.FileHandler
        formatter:   rootFormatter
        filename:    'logs/server.log'
loggers:
    root:
        level:       DEBUG
        handlers:    [consoleHandler]
    main:
        level:       DEBUG
        handlers:   [consoleHandler, fileHandler]